//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financeiro4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans
    {
        public int id { get; set; }
        public int cliente_id { get; set; }
        public int tipo_id { get; set; }
        public string data { get; set; }
        public decimal valor { get; set; }
        public byte credito { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual tipos tipos { get; set; }
    }
}
