//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP2SW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int id { get; set; }
        public int cliente_id { get; set; }
        public int produto_id { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<decimal> preco { get; set; }
        public string data { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual produtos produtos { get; set; }
    }
}
